services:
  db:
    image: postgres:16-alpine
    container_name: companion_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: companion
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app -d companion']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    container_name: companion_api
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI

volumes:
  db:
